import type { Engine } from '../types'
import { generateTeam as mockGenerate } from '../mock/generate'
import { generateTeam as localGenerate } from './local'

// The engine registry. Adding a backend = adding an entry here.
export const ENGINES: Engine[] = [
  {
    id: 'mock',
    label: 'Mock',
    description: 'Archived teams generated by the v1 lab (7B + RAG). No model running.',
    available: true,
    generateTeam: mockGenerate,
  },
  {
    id: 'local',
    label: 'Local (baseline)',
    description: 'The naked qwen2.5:1.5b over local Ollama, no RAG. Needs Ollama running.',
    available: true,
    generateTeam: localGenerate,
  },
  {
    id: 'browser-ai',
    label: 'Browser AI',
    description:
      'A 1.5B model fine-tuned for team building + live retrieval, running on your own GPU via WebGPU. Coming soon.',
    available: false,
    generateTeam: async () => {
      throw new Error('not implemented yet')
    },
  },
]

export const DEFAULT_ENGINE = ENGINES[0]
