import type { Engine } from '../types'
import { generateTeam as mockGenerate } from '../mock/generate'
import { generateTeam as localRagGenerate } from './localRag'
import { generateTeam as browserAiGenerate } from './browserAi'

// The engine registry. Adding a backend = adding an entry here.
export const ENGINES: Engine[] = [
  {
    id: 'mock',
    label: 'Mock',
    description: 'Archived teams generated by the v1 lab (7B + RAG). No model running.',
    available: true,
    generateTeam: mockGenerate,
  },
  {
    id: 'local-rag',
    label: 'Local (3B + RAG)',
    description:
      'Browser-side RAG (retrieval + embeddings) + a validate→repair loop, generating with qwen2.5:3b over Ollama. The dev preview of the Pages build, which swaps Ollama for WebLLM. Needs Ollama running.',
    available: true,
    generateTeam: localRagGenerate,
  },
  {
    id: 'browser-ai',
    label: 'Browser AI',
    description:
      'Qwen2.5-3B + live retrieval, running entirely on your own GPU via WebGPU. No server; the model (~1.9 GB) downloads once and is cached.',
    available: true,
    generateTeam: browserAiGenerate,
  },
]

export const DEFAULT_ENGINE = ENGINES[0]
